### ISSUE TITLE
Audio falsch

### ISSUE THREAD

**Issue by Lunnaris01** [aomizu/anki#1]
Die Karte für "Vielen Dank!" /（どうも）ありがとう（ございます). Hat eine Falsche Audio

**Comment by tairasu** [comment]
Danke für den Hinweis! Diesen Fehler habe ich vor langer Zeit bei meinem eigenen Deck entfernt, aber nicht hier auf Github. Die falsche Audio habe ich jetzt auch auf GitHub entfernt.
